name: Build

env:
#  if: (github.event_name == 'schedule')
#  GITHUB_ENV: https://docs.github.com/en/actions/learn-github-actions/environment-variables#about-environment-variables
  FF_VERSION: ${{ vars.FF_VER }} # TODO: latest release if triggered by schedule
  LLVM_VER: ${{ vars.LLVM_VER }}
  LLVM_VER_DEFAULT: 20
  NINJA_STATUS: '[%f/%t %e %r]'
  SF_PW_MAPPED: ${{ secrets.SF_PW }}
  SF_USER_MAPPED: ${{ secrets.SF_USER }}
  VC_LTL_VER: ${{ vars.VC_LTL_VER }}

jobs:
  Apple:
    # See: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix
    runs-on: macos-15
    env:
      TARGET_OS: ${{ matrix.target }}
      CONFIG_SUFFIX: -${{ matrix.config }}
    strategy:
      fail-fast: false
      matrix:
        config: [default,lite,lite-lto] # lto reduce about 300KB for lite build
        target: [macOS,iOS,iOSSimulator,visionOS,visionOSSimulator,tvOS,tvOSSimulator,macCatalyst]
        exclude:
          - config: default
            target: iOS
          - config: default
            target: iOSSimulator
          - config: lite
            target: iOSSimulator
          - config: default
            target: macCatalyst
          - config: lite
            target: macCatalyst
          - config: default
            target: tvOS
          - config: default
            target: tvOSSimulator
          - config: lite
            target: tvOSSimulator
          - config: default
            target: visionOS
          - config: lite # llvm-ar-17 merged visionOS lto libs has wrong contents (/,//,*.o/)
            target: visionOS
          - config: default
            target: visionOSSimulator
          - config: lite
            target: visionOSSimulator
    steps:
    - uses: actions/checkout@v5
    - name: Setup Xcode
      run: sudo xcode-select -s /Applications/Xcode_${{ vars.XCODE }}.app
    - name: Create Build Environment
      shell: bash
      env:
        DEVTOOLS_CACHE_HIT: ${{ steps.devtools-cache.outputs.cache-hit }}
        EXTERNAL_DEP_CACHE_HIT: ${{ steps.external-dep-cache.outputs.cache-hit }}
      run: ./tools/ci-before-build.sh
    - name: Configure and Build
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      run: |
        export FFSRC=$PWD/ffmpeg-${FF_VERSION}
        [[ "${TARGET_OS}" == "macOS" ]] && export USER_OPT="--enable-libshaderc"
        ./avbuild.sh ${TARGET_OS}
    - name: Make SDK
      shell: bash
      run: ./tools/ci-after-build.sh
    - name: Archieve SDK
      uses: actions/upload-artifact@v4
      with:
        name: ffmpeg-${{ env.FF_VERSION }}-${{ env.TARGET_OS }}-${{ matrix.config }}
        path: ffmpeg-*.tar.xz


  VS2022LTL:
    runs-on: windows-2022
    env:
      TARGET_OS: ${{ matrix.target }}
      CONFIG_SUFFIX: -${{ matrix.config }}
    strategy:
      fail-fast: false
      matrix:
        config: [lite,default]
        target: [windows-desktop]
    steps:
    - uses: actions/checkout@v5
      with:
        submodules: 'recursive'
    - name: 'Restore dep cache'
      id: dep-cache
      uses: actions/cache@v4
      with:
        path: VC-LTL
        key: dep-${{ vars.VC_LTL_VER }}
    - if: ${{ steps.dep-cache.outputs.cache-hit != 'true' }}
      name: Get VC-LTL
      shell: bash
      run: |
        curl -kL -o ltl.7z https://github.com/Chuyu-Team/VC-LTL5/releases/download/v${{ vars.VC_LTL_VER }}/VC-LTL-${{ vars.VC_LTL_VER }}-Binary.7z
        7z x ltl.7z -oVC-LTL
    - name: Create Build Environment
      shell: cmd
      run: |
        set FF_BRANCH=%FF_VERSION%
        if not [%FF_BRANCH%]==[master] set FF_BRANCH=release/%FF_VERSION%
        git clone -b %FF_BRANCH% --depth 1 --no-tags https://git.ffmpeg.org/ffmpeg.git ffmpeg-%FF_VERSION%
        if not [%CONFIG_SUFFIX%]==[-default] copy /y config%CONFIG_SUFFIX%.sh config.sh
    - uses: msys2/setup-msys2@v2
      with:
        release: false # disable installation cache, so exe path in avbuild.sh is correct
        msystem: MSYS
        update: true
        install: >-
          make
          diffutils
          patch
          pkg-config
          nasm
          yasm
    - name: Install dev packages
      shell: msys2 {0}
      run: |
        wget https://sourceforge.net/projects/avbuild/files/dep/dep.7z/download -O dep.7z
    - name: Configure and Build
      shell: cmd
      run: |
        7z x -y dep.7z -otools
        set VC_LTL_DIR=%CD%\VC-LTL
        set PKG_CONFIG_PATH_MFX=%CD%\tools\dep\VS2022LTL\lib\pkgconfig
        set MSYS2_DIR=C:\msys64
        set HOME=%CD%
        set FFSRC=%CD%\ffmpeg-%FF_VERSION%
        set BUILD_NOW=true
        set USER_OPT=--enable-libshaderc
        tools\vcbuild.bat VS2022 %TARGET_OS%10 all
    - name: Make SDK
      shell: cmd
      run: |
        set SDK_NAME=ffmpeg-%FF_VERSION%-%TARGET_OS%-vs2022ltl%CONFIG_SUFFIX%
        move sdk* %SDK_NAME%
        7z a -ssc -m0=lzma2 -mx=9 -ms=on -mf=off -xr!*.pdb %SDK_NAME%.7z %SDK_NAME%
        7z a -ssc -m0=lzma2 -mx=9 -ms=on -mf=off %SDK_NAME%-pdb.7z -ir!%SDK_NAME%\*.pdb
    - name: Archieve SDK
      uses: actions/upload-artifact@v4
      with:
        name: ffmpeg-${{ env.FF_VERSION }}-${{ env.TARGET_OS }}-VS2022ltl${{ matrix.config }}
        path: ffmpeg-*.7z

  Android:
    runs-on: macos-15
    env:
      TARGET_OS: android
      CONFIG_SUFFIX: -${{ matrix.config }}
    strategy:
      fail-fast: false
      matrix:
        config: [lite,lite-lto]
    steps:
    - uses: actions/checkout@v5
    - name: 'Restore sysroot cache'
      id: sysroot-cache
      uses: actions/cache@v4
      with:
        path: /tmp/sysroot
        key: sysroot-${{ env.TARGET_OS }}-${{ vars.LINUX_SYSROOT_ID }}
    - name: Create Build Environment
      shell: bash
      env:
        SYSROOT_CACHE_HIT: ${{ steps.sysroot-cache.outputs.cache-hit }}
      run: ./tools/ci-before-build.sh
    - name: Configure and Build 32bit
      shell: bash
      run: |
        export ANDROID_NDK=$ANDROID_NDK_LATEST_HOME
        export FFSRC=$PWD/ffmpeg-${FF_VERSION}
        export USER_OPT="--enable-wolfssl"
        ./avbuild.sh ${TARGET_OS} "armv7 x86"
        mv sdk-android-clang{,32}
    - name: Configure and Build 64bit
      shell: bash
      run: |
        export ANDROID_NDK=$ANDROID_NDK_LATEST_HOME
        export FFSRC=$PWD/ffmpeg-${FF_VERSION}
        export USER_OPT="--enable-wolfssl"
        ./avbuild.sh ${TARGET_OS} "arm64 x86_64"
        rsync -auv --ignore-existing  sdk-android-clang{32/*,}
        rm -rf sdk-android-clang32
    - name: Make SDK
      shell: bash
      run: ./tools/ci-after-build.sh
    - name: Archieve SDK
      uses: actions/upload-artifact@v4
      with:
        name: ffmpeg-${{ env.FF_VERSION }}-${{ env.TARGET_OS }}-${{ matrix.config }}
        path: ffmpeg-*.tar.xz
